(function(e){let n=window.WPD.ajaxsearchpro.helpers;e.fn.extend(window.WPD.ajaxsearchpro.plugin,{liveLoad:function(c,h,b,m){function k(d){var l=new DOMParser;let q=l.parseFromString(d,"text/html"),p=e(q);a.o.statistics&&a.stat_addKeyword(a.o.id,a.n.text.val());if(""!=d&&0<p.length&&0<p.find(c).length){d=d.replace(/&asp_force_reset_pagination=1/gmi,"");d=d.replace(/%26asp_force_reset_pagination%3D1/gmi,"");d=d.replace(/&#038;asp_force_reset_pagination=1/gmi,"");d=n.Hooks.applyFilters("asp_live_load_html",
d,a.o.id,a.o.iid);d=n.wp_hooks_apply_filters("asp_live_load_html",d,a.o.id,a.o.iid);p=e(l.parseFromString(d,"text/html"));f.get(0).parentNode.replaceChild(p.find(c).get(0),f.get(0));f=e(c).first();b&&(document.title=q.title,history.pushState({},null,h));!1!==c.indexOf("asp_es_")&&"undefined"!=typeof elementorFrontend&&"undefined"!=typeof elementorFrontend.init&&(l=f.parent().data("widget_type"),""!=l&&"undefined"!=typeof jQuery&&elementorFrontend.hooks.doAction("frontend/element_ready/"+l,jQuery(f.parent().get(0))),
a.fixElementorPostPagination(h),a.n.s.trigger("asp_elementor_results",[a.o.id,a.o.iid,f],!0,!0));e(c).first().find(".woocommerce-ordering").on("change","select.orderby",function(){e(this).closest("form").trigger("submit")});if(1==a.o.singleHighlight)e(c).find("a").on("click",function(){localStorage.removeItem("asp_phrase_highlight");""!=n.unqoutePhrase(a.n.text.val())&&localStorage.setItem("asp_phrase_highlight",JSON.stringify({phrase:n.unqoutePhrase(a.n.text.val()),id:a.o.id}))});ASP.initialize();
a.lastSuccesfulSearch=e("form",a.n.searchsettings).serialize()+a.n.text.val().trim();a.lastSearchData=d}else 0==p.find(c).length&&!1!==c.indexOf("asp_es_")&&(f.html(""),a.lastSuccesfulSearch=e("form",a.n.searchsettings).serialize()+a.n.text.val().trim(),a.lastSearchData=d,a.n.s.trigger("asp_elementor_results",[a.o.id,a.o.iid,f],!0,!0));a.n.s.trigger("asp_search_end",[a.o.id,a.o.iid,a.n.text.val(),d],!0,!0);a.gaEvent("search_end",{results_count:"unknown"});a.gaPageview(a.n.text.val());a.hideLoader();
f.css("opacity",1);a.searching=!1;""!=a.n.text.val()&&a.n.proclose.css({display:"block"})}if("body"==c||"html"==c)return console.log("Ajax Search Pro: Do not use html or body as the live loader selector."),!1;""==ASP.pageHTML&&"undefined"===typeof ASP._ajax_page_html&&(ASP._ajax_page_html=!0,e.fn.ajax({url:location.href,method:"GET",success:function(d){ASP.pageHTML=d},dataType:"html"}));b="undefined"==typeof b?!0:b;m="undefined"==typeof m?!1:m;let g=".search-content #content #Content div[role=main] main[role=main] div.theme-content div.td-ss-main-content main.l-content #primary".split(" ");
"#main"!=c&&g.unshift("#main");if(1>e(c).length&&(g.forEach(function(d,l){if(0<e(l).length)return c=l,!1}),1>e(c).length))return console.log("Ajax Search Pro: The live search selector does not exist on the page."),!1;-1<c.indexOf("asp_es_")&&(c+=" .elementor-widget-container");let f=e(c).first(),a=this;a.searchAbort();f.css("opacity",.4);m||1!=a.n.searchsettings.find("input[name=filters_initial]").val()||""!=a.n.text.val()?a.post=e.fn.ajax({url:h,method:"GET",success:function(d){k(d)},dataType:"html",
fail:function(d){f.css("opacity",1);d.aborted||(f.html("This request has failed. Please check your connection."),a.hideLoader(),a.searching=!1,a.n.proclose.css({display:"block"}))}}):window.WPD.intervalUntilExecute(function(){k(ASP.pageHTML)},function(){return""!=ASP.pageHTML})},getCurrentLiveURL:function(){var c="asp_ls="+n.nicePhrase(this.n.text.val());let h="&",b=window.location.href;b=-1<b.indexOf("asp_ls=")?b.slice(0,b.indexOf("asp_ls=")):b;b=-1<b.indexOf("asp_ls&")?b.slice(0,b.indexOf("asp_ls&")):
b;b=-1<b.indexOf("p_asid=")?b.slice(0,b.indexOf("p_asid=")):b;b=-1<b.indexOf("asp_")?b.slice(0,b.indexOf("asp_")):b;-1===b.indexOf("?")&&(h="?");c=b+h+c+"&asp_active=1&asp_force_reset_pagination=1&p_asid="+this.o.id+"&p_asp_data=1&"+e("form",this.n.searchsettings).serialize();return c=c.replace("?&","?")},fixElementorPostPagination:function(c){let h=this,b=e(".asp_es_"+h.o.id);if(0<b.length){let m=c.indexOf("?");if(0<=m){let k=c.substring(m+1);if(k&&(k=k.replace(/&asp_force_reset_pagination=1/gmi,
""),b.find(".elementor-pagination a, .elementor-widget-container .woocommerce-pagination a").each(function(){let g=e(this).attr("href");0>g.indexOf("asp_ls=")&&0>g.indexOf("asp_ls&")&&(0>g.indexOf("?")?e(this).attr("href",g+"?"+k):e(this).attr("href",g+"&"+k))}),0<b.length))b.find(".elementor-pagination a, .elementor-widget-container .woocommerce-pagination a").on("click",function(g){g.preventDefault();g.stopImmediatePropagation();g.stopPropagation();h.showLoader();h.liveLoad(".asp_es_"+h.o.id,e(this).attr("href"),
!1,!0)})}}}})})(WPD.dom);
